/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedLoader: typeof import('./src/components/landing/AnimatedLoader.vue')['default']
    AuthModal: typeof import('./src/components/auth/AuthModal.vue')['default']
    BreakTheWebsite: typeof import('./src/components/landing/BreakTheWebsite.vue')['default']
    Collaboration: typeof import('./src/components/landing/Collaboration.vue')['default']
    ComponentsSystem: typeof import('./src/components/landing/ComponentsSystem.vue')['default']
    DesignGuide: typeof import('./src/components/landing/DesignGuide.vue')['default']
    FinalCTA: typeof import('./src/components/landing/FinalCTA.vue')['default']
    FreeAIHelper: typeof import('./src/components/landing/FreeAIHelper.vue')['default']
    IconLucideAlignCenter: typeof import('~icons/lucide/align-center')['default']
    IconLucideAlignHorizontalDistributeCenter: typeof import('~icons/lucide/align-horizontal-distribute-center')['default']
    IconLucideAlignLeft: typeof import('~icons/lucide/align-left')['default']
    IconLucideAlignRight: typeof import('~icons/lucide/align-right')['default']
    IconLucideAlignVerticalDistributeCenter: typeof import('~icons/lucide/align-vertical-distribute-center')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideFrame: typeof import('~icons/lucide/frame')['default']
    IconLucideHand: typeof import('~icons/lucide/hand')['default']
    IconLucideImage: typeof import('~icons/lucide/image')['default']
    IconLucideLayoutGrid: typeof import('~icons/lucide/layout-grid')['default']
    IconLucideMessageSquare: typeof import('~icons/lucide/message-square')['default']
    IconLucideMousePointer: typeof import('~icons/lucide/mouse-pointer')['default']
    IconLucidePalette: typeof import('~icons/lucide/palette')['default']
    IconLucidePenTool: typeof import('~icons/lucide/pen-tool')['default']
    IconLucideSparkles: typeof import('~icons/lucide/sparkles')['default']
    IconLucideSquare: typeof import('~icons/lucide/square')['default']
    IconLucideTag: typeof import('~icons/lucide/tag')['default']
    IconLucideType: typeof import('~icons/lucide/type')['default']
    LandingFeatures: typeof import('./src/components/landing/LandingFeatures.vue')['default']
    LandingFooter: typeof import('./src/components/landing/LandingFooter.vue')['default']
    LandingHero: typeof import('./src/components/landing/LandingHero.vue')['default']
    LandingNavbar: typeof import('./src/components/landing/LandingNavbar.vue')['default']
    MarbleBackground: typeof import('./src/components/landing/MarbleBackground.vue')['default']
    NexLogo: typeof import('./src/components/landing/NexLogo.vue')['default']
    Pricing: typeof import('./src/components/landing/Pricing.vue')['default']
    ProductShowcase: typeof import('./src/components/landing/ProductShowcase.vue')['default']
    Prototyping: typeof import('./src/components/landing/Prototyping.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Typography: typeof import('./src/components/landing/Typography.vue')['default']
    UserStatusModal: typeof import('./src/components/auth/UserStatusModal.vue')['default']
    WhyNex: typeof import('./src/components/landing/WhyNex.vue')['default']
  }
}
